name: My GitHub workflow
run-name: GitHub login AWS
on: 
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1   
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello World
        run: echo "Hello World 😎"
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 296851752807.dkr.ecr.us-east-1.amazonaws.com

      - name: Build, tag, and push image to Amazon ECR
 
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build -t node-app .
          docker tag node-app:latest 296851752807.dkr.ecr.us-east-1.amazonaws.com/node-app:latest
          docker push 296851752807.dkr.ecr.us-east-1.amazonaws.com/node-app:latest
    
